<?php
namespace Esteem_Meta_Lead_Capture\Controllers;
class Meta_settings extends \App\Controllers\Security_Controller {
    private function admin_only() { if (!$this->login_user->is_admin) app_redirect('forbidden'); }
    public function index() { $this->admin_only(); $service=new \Esteem_Meta_Lead_Capture\Libraries\Meta_lead_service(); $view=array('settings'=>$service->settings(),'owners'=>$this->owners(),'callback_url'=>get_uri('esteem_meta_lead_capture/webhook')); return $this->template->rander('Esteem_Meta_Lead_Capture\\Views\\settings\\index',$view); }
    public function save() { $this->admin_only(); $this->validate_submitted_data(array('enabled'=>'numeric','api_version'=>'required','default_status'=>'required')); $service=new \Esteem_Meta_Lead_Capture\Libraries\Meta_lead_service(); $settings=$service->settings(); $owners=array_map('intval',(array)$this->request->getPost('owner_ids')); $allowed=array_map('intval',array_column($this->owners(),'id')); $owners=array_values(array_intersect($owners,$allowed)); $version=trim((string)$this->request->getPost('api_version')); if(!preg_match('/^v[0-9]+(?:\.[0-9]+)?$/',$version) || !$this->status_exists($this->request->getPost('default_status'))) { echo json_encode(array('success'=>false,'message'=>'Enter a valid Meta API version and an existing lead status.')); return; } $data=array('enabled'=>$this->request->getPost('enabled')?'1':'0','app_id'=>trim((string)$this->request->getPost('app_id')),'page_id'=>preg_replace('/\D+/','',(string)$this->request->getPost('page_id')),'api_version'=>$version,'default_status'=>trim((string)$this->request->getPost('default_status')),'owner_ids'=>implode(',',$owners)); foreach(array('app_secret','page_access_token','verify_token') as $key) { $value=trim((string)$this->request->getPost($key)); if($value!=='')$data[$key]=$value; } if($data['enabled']==='1' && (!$data['page_id'] || !$owners || (!$data['page_access_token'] && !$settings['page_access_token']) || (!$data['verify_token'] && !$settings['verify_token']) || (!$data['app_secret'] && !$settings['app_secret']))) { echo json_encode(array('success'=>false,'message'=>'Complete the required credentials, Page ID and at least one owner before enabling.')); return; } $service->save_settings($data); echo json_encode(array('success'=>true,'message'=>'Meta Lead Capture settings saved.')); }
    public function test_connection() { $this->admin_only(); $s=(new \Esteem_Meta_Lead_Capture\Libraries\Meta_lead_service())->settings(); $result=(new \Esteem_Meta_Lead_Capture\Libraries\Meta_lead_service())->graph_get($s['page_id'].'?fields=id,name',$s); echo json_encode($result['ok']?array('success'=>true,'message'=>'Connection successful. Page credentials are valid.'):array('success'=>false,'message'=>'Connection failed: '.$result['error'])); }
    private function status_exists($title) { return (bool)db_connect('default')->query('SELECT id FROM '.get_db_prefix().'lead_status WHERE deleted=0 AND LOWER(title)=? LIMIT 1',array(strtolower(trim((string)$title))))->getRow(); }
    private function owners() { $db=db_connect('default'); $allowed=array('Harry Smith','Neil White','Mark White','John Adams','John Adam'); $rows=$db->query('SELECT id, CONCAT(first_name," ",last_name) AS name FROM '.get_db_prefix().'users WHERE deleted=0 AND status="active" AND user_type="staff" ORDER BY first_name,last_name')->getResultArray(); return array_values(array_filter($rows,function($row)use($allowed){return in_array(trim($row['name']),$allowed,true);})); }
}
