<?php
namespace Esteem_Email_Marketing\Controllers;
use App\Controllers\Security_Controller;
use Esteem_Email_Marketing\Libraries\Recipient_Service;
class Campaign_Actions extends Security_Controller {
 private $db;private $p;
 public function __construct(){parent::__construct();$this->access_only_admin();$this->db=db_connect('default');$this->p=get_db_prefix();}
 public function queue_campaign($id){if(!email_marketing_mail_configured())return redirect()->back()->with('error','CRM email transport is not configured; campaign was not queued.');$c=$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->get()->getRow();if(!$c)return redirect()->back()->with('error','Campaign not found.');$filters=json_decode((string)$c->segment_filters,true);if(!is_array($filters)||!count($filters))return redirect()->back()->with('error','No saved recipient filters exist; campaign was not queued.');if(email_marketing_setting('test_mode','1')==='1'){$email=filter_var($c->test_recipient??'',FILTER_VALIDATE_EMAIL);if(!$email||!in_array(strtolower($email),email_marketing_approved_test_emails(),true))return redirect()->back()->with('error','Test mode blocks this address; add it to the approved test-email list.');$rows=[(object)['id'=>(int)$c->test_contact_id,'user_type'=>'test','email'=>strtolower($email),'first_name'=>'Test','last_name'=>'Recipient']];}elseif(!empty($filters['imported'])){$rows=$this->db->table($this->p.'email_campaign_recipients')->where(['campaign_id'=>(int)$id,'status'=>'queued'])->get()->getResult();foreach($rows as $row)$row->user_type=$row->entity_type;}else{$rows=(new Recipient_Service())->query($filters,100000,0);}if(!$rows)return redirect()->back()->with('error','Saved filters returned 0 eligible Opted In recipients.');$eligible=count($rows);$count=0;foreach($rows as $r){$email=strtolower(trim($r->email));if(!$email||$this->db->table($this->p.'email_suppressions')->where('email',$email)->countAllResults())continue;if(!empty($filters['imported'])){$count++;continue;}if($this->db->table($this->p.'email_campaign_recipients')->ignore(true)->insert(['campaign_id'=>(int)$id,'entity_type'=>$r->user_type,'entity_id'=>(int)$r->id,'email'=>$email,'recipient_name'=>trim(($r->first_name??'').' '.($r->last_name??'')),'status'=>'queued','is_test'=>(int)($r->user_type==='test'),'queued_at'=>date('Y-m-d H:i:s')]))$count++;}if(!$count)return redirect()->back()->with('error','No new eligible recipients were queued.');$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->update(['status'=>$c->send_at?'scheduled':'sending','last_eligible_count'=>$eligible]);return redirect()->to(site_url('email_marketing'))->with('success',$count.' recipient(s) queued using saved filters. Eligible count for this run: '.$eligible.'.');}
 public function import_csv($id){$campaign=$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->get()->getRow();if(!$campaign)return redirect()->back()->with('error','Campaign not found.');$file=$this->request->getFile('csv_file');if(!$file||!$file->isValid()||$file->getSize()>2097152)return redirect()->back()->with('error','Upload a valid CSV file up to 2 MB.');$handle=fopen($file->getTempName(),'rb');$header=fgetcsv($handle);if(!$header){if(is_resource($handle))fclose($handle);return redirect()->back()->with('error','CSV is empty.');}$header=array_map(function($v){return strtolower(trim((string)$v));},$header);if(!in_array('email',$header,true)||!in_array('consent',$header,true)){if(is_resource($handle))fclose($handle);return redirect()->back()->with('error','CSV must contain email and consent columns. Consent must be Opted In.');}$added=0;$skipped=0;$row_number=1;while(($values=fgetcsv($handle))!==false){$row_number++;$row=[];foreach($header as $i=>$key)$row[$key]=trim((string)($values[$i]??''));$email=filter_var($row['email']??'',FILTER_VALIDATE_EMAIL);if(!$email||strcasecmp($row['consent']??'','Opted In')!==0||strcasecmp($row['do_not_contact']??'','yes')===0||$this->db->table($this->p.'email_suppressions')->where('email',strtolower($email))->countAllResults()){$skipped++;continue;}$ok=$this->db->table($this->p.'email_campaign_recipients')->ignore(true)->insert(['campaign_id'=>(int)$id,'entity_type'=>'import','entity_id'=>0,'email'=>strtolower($email),'recipient_name'=>trim(($row['first_name']??'').' '.($row['last_name']??'')),'status'=>'queued','queued_at'=>date('Y-m-d H:i:s')]);if($ok)$added++;else$skipped++;}if(is_resource($handle))fclose($handle);$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->update(['segment_filters'=>json_encode(['imported'=>1])]);return redirect()->to(site_url('email_marketing/edit/'.(int)$id))->with('success',$added.' imported recipient(s) added. '.$skipped.' row(s) skipped for invalid, non-consented, suppressed, or Do Not Contact data.');}
 public function logs($id){$rows=$this->db->table($this->p.'email_campaign_recipients')->where('campaign_id',(int)$id)->orderBy('id','DESC')->get()->getResult();return $this->template->rander('Esteem_Email_Marketing\\Views\\email_marketing\\logs',['rows'=>$rows,'campaign_id'=>(int)$id]);}
 public function delete_campaign($id){$id=(int)$id;$campaign=$this->db->table($this->p.'email_campaigns')->where('id',$id)->get()->getRow();if(!$campaign)return redirect()->back()->with('error','Campaign not found.');$this->db->transStart();$this->db->table($this->p.'email_campaign_recipients')->where('campaign_id',$id)->delete();$this->db->table($this->p.'email_campaigns')->where('id',$id)->delete();$this->db->transComplete();if(!$this->db->transStatus())return redirect()->back()->with('error','Campaign could not be deleted.');return redirect()->to(site_url('email_marketing'))->with('success','Campaign deleted.');}
}
