<?php
namespace Esteem_Email_Marketing\Controllers;
use App\Controllers\Security_Controller;

class Email_Marketing extends Security_Controller
{
    private $db; private $p;
    public function __construct(){parent::__construct();$this->access_only_admin();$this->db=db_connect('default');$this->p=get_db_prefix();}
    public function index(){return $this->template->rander('Esteem_Email_Marketing\\Views\\email_marketing\\index',['campaigns'=>$this->db->table($this->p.'email_campaigns')->orderBy('id','DESC')->get()->getResult(),'settings'=>$this->settings_values()]);}
    public function create(){return $this->template->rander('Esteem_Email_Marketing\\Views\\email_marketing\\form',['campaign'=>null,'filters'=>[],'settings'=>$this->settings_values(),'test_contacts'=>$this->test_contacts()]);}
    public function edit($id){$campaign=$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->get()->getRow();if(!$campaign)return redirect()->to(site_url('email_marketing'))->with('error','Campaign not found.');$filters=json_decode((string)$campaign->segment_filters,true);return $this->template->rander('Esteem_Email_Marketing\\Views\\email_marketing\\form',['campaign'=>$campaign,'filters'=>is_array($filters)?$filters:[],'settings'=>$this->settings_values(),'test_contacts'=>$this->test_contacts()]);}
    public function save()
    {
        $d=$this->request->getPost();$filters=[];foreach(['type','owner_id','status_id','source_id','state','suburb','postcode','created_from','created_to','labels'] as $key)if(isset($d[$key])&&$d[$key]!=='')$filters[$key]=is_numeric($d[$key])?(int)$d[$key]:trim((string)$d[$key]);
        $test_id=(int)($d['test_contact_id']??0);$contact=$this->eligible_test_contact($test_id);if(email_marketing_setting('test_mode','1')==='1'&&(!$contact||!in_array(strtolower($contact->email),email_marketing_approved_test_emails(),true)))return redirect()->back()->with('error','Test mode requires one approved CRM test contact with Opted In consent, Active email status, no suppression, and no Do Not Contact flag.');
        $data=['name'=>trim((string)($d['name']??'')),'subject'=>trim((string)($d['subject']??'')),'preview_text'=>trim((string)($d['preview_text']??'')),'html_content'=>(string)($d['html_content']??''),'sender_name'=>trim((string)($d['sender_name']??email_marketing_setting('default_sender_name','Esteem Energy'))),'reply_to'=>filter_var($d['reply_to']??'',FILTER_VALIDATE_EMAIL)?:'','test_recipient'=>$contact?strtolower($contact->email):'','test_contact_id'=>$test_id,'test_contact_type'=>$contact?($contact->is_lead?'lead':'client'):'','segment_filters'=>json_encode($filters),'send_at'=>!empty($d['send_at'])?date('Y-m-d H:i:s',strtotime($d['send_at'])):null,'status'=>'draft','created_by'=>(int)$this->login_user->id,'created_at'=>date('Y-m-d H:i:s')];
        if(!$data['name']||!$data['subject']||!$data['html_content'])return redirect()->back()->with('error','Name, subject and HTML content are required.');$this->db->table($this->p.'email_campaigns')->insert($data);$id=(int)$this->db->insertID();$this->history($id,'','draft');return redirect()->to(site_url('email_marketing/edit/'.$id))->with('success','Campaign saved as Draft. Approved test contact selected.');
    }
    public function send_test($id)
    {
        if(!email_marketing_mail_configured())return redirect()->back()->with('error','CRM email transport is not configured.');if(email_marketing_setting('test_mode','1')!=='1')return redirect()->back()->with('error','Test mode must be enabled for test sends.');$c=$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->get()->getRow();if(!$c)return redirect()->back()->with('error','Campaign not found.');$contact=$this->eligible_test_contact((int)$c->test_contact_id);$email=strtolower((string)($contact->email??''));if(!$contact||$email!==strtolower((string)$c->test_recipient)||!in_array($email,email_marketing_approved_test_emails(),true)){ $this->test_log($id,(int)($c->test_contact_id??0),$email,'blocked','Test contact is not eligible or is not approved.'); return redirect()->back()->with('error','Test contact is no longer eligible or is not approved in Test Mode settings.'); }$ok=$this->db->table($this->p.'email_campaign_recipients')->ignore(true)->insert(['campaign_id'=>(int)$id,'entity_type'=>'test','entity_id'=>(int)$c->test_contact_id,'email'=>$email,'recipient_name'=>trim(($contact->first_name??'').' '.($contact->last_name??'')),'status'=>'queued','is_test'=>1,'queued_at'=>date('Y-m-d H:i:s')]);if(!$ok){$this->test_log($id,(int)$c->test_contact_id,$email,'failed','Test email was already queued or could not be logged.');return redirect()->back()->with('error','Test email was already queued for this campaign or could not be logged.');}$this->test_log($id,(int)$c->test_contact_id,$email,'queued','TEST EMAIL queued');$old=$c->status;$this->db->table($this->p.'email_campaigns')->where('id',(int)$id)->update(['status'=>'sending','updated_at'=>date('Y-m-d H:i:s')]);$this->history($id,$old,'sending');return redirect()->to(site_url('email_marketing'))->with('success','TEST EMAIL queued for the approved test contact only. Run CRM cron to process it.');
    }
    public function settings(){return $this->template->rander('Esteem_Email_Marketing\\Views\\email_marketing\\settings',['settings'=>$this->settings_values(),'mail_configured'=>email_marketing_mail_configured(),'approved_test_emails'=>email_marketing_approved_test_emails()]);}
    public function automation(){return $this->template->rander('Esteem_Email_Marketing\\Views\\email_marketing\\automation',['rules'=>$this->db->table($this->p.'email_automation_rules')->orderBy('id','DESC')->get()->getResult()]);}
    public function save_rule(){ $d=$this->request->getPost();$this->db->table($this->p.'email_automation_rules')->insert(['name'=>trim((string)($d['name']??'')),'trigger_type'=>in_array($d['trigger_type']??'', ['new_lead','quote_sent','no_response'],true)?$d['trigger_type']:'new_lead','delay_minutes'=>max(0,(int)($d['delay_minutes']??0)),'template_id'=>(int)($d['template_id']??0),'enabled'=>0,'created_by'=>(int)$this->login_user->id,'created_at'=>date('Y-m-d H:i:s')]);return redirect()->to(site_url('email_marketing/automation'))->with('success','Automation rule saved disabled.');}
    public function save_settings(){foreach(['enabled','default_sender_name','default_reply_to','batch_size','delay_between_messages','company_footer','test_mode','approved_test_emails'] as $key){$value=(string)$this->request->getPost($key);$value=$key==='approved_test_emails'?implode("\n",email_marketing_approved_test_emails_from($value)):($key==='enabled'||$key==='test_mode'?($value==='1'?'1':'0'):($key==='batch_size'?max(1,min(500,(int)$value)):$value));$this->db->table($this->p.'email_marketing_settings')->replace(['setting_name'=>$key,'setting_value'=>$value]);}return redirect()->to(site_url('email_marketing/settings'))->with('success','Settings saved.');}
    public function unsubscribe($token){$raw=base64_decode(strtr($token,'-_','+/'));if(!$raw||strpos($raw,'|')===false)return $this->response->setStatusCode(400)->setBody('Invalid unsubscribe link.');[$hash,$email]=explode('|',$raw,2);if(!hash_equals(hash_hmac('sha256',strtolower($email),encryption_key(),true),$hash))return $this->response->setStatusCode(403)->setBody('Invalid unsubscribe link.');$this->db->table($this->p.'email_suppressions')->ignore(true)->insert(['email'=>strtolower($email),'reason'=>'unsubscribe','created_at'=>date('Y-m-d H:i:s')]);$this->db->table($this->p.'email_campaign_recipients')->where('email',strtolower($email))->where('status','queued')->update(['status'=>'unsubscribed']);return $this->response->setBody('You have been unsubscribed from Esteem Energy marketing emails.');}
    private function settings_values(){ $out=[];foreach($this->db->table($this->p.'email_marketing_settings')->get()->getResult() as $row)$out[$row->setting_name]=$row->setting_value;return $out; }
    private function test_contacts(){return $this->db->query("SELECT u.id,u.first_name,u.last_name,u.email,c.is_lead FROM {$this->p}users u JOIN {$this->p}clients c ON c.id=u.client_id AND c.deleted=0 LEFT JOIN {$this->p}marketing_consent mc ON mc.entity_id=u.id AND mc.entity_type=CASE WHEN c.is_lead=1 THEN 'lead' ELSE 'client' END WHERE u.deleted=0 AND u.is_primary_contact=1 AND u.email<>'' AND COALESCE(mc.consent,'Unknown')='Opted In' AND NOT EXISTS(SELECT 1 FROM {$this->p}email_suppressions es WHERE es.email=LOWER(u.email)) AND LOWER(COALESCE(c.labels,'')) NOT LIKE '%do not contact%' ORDER BY u.first_name,u.last_name")->getResult();}
    private function eligible_test_contact($id){foreach($this->test_contacts() as $contact)if((int)$contact->id===$id)return $contact;return null;}
    private function history($id,$from,$to){$this->db->table($this->p.'email_campaign_status_history')->insert(['campaign_id'=>(int)$id,'from_status'=>(string)$from,'to_status'=>(string)$to,'changed_by'=>(int)$this->login_user->id,'changed_at'=>date('Y-m-d H:i:s')]);}
    private function test_log($campaign_id,$contact_id,$email,$status,$error){$this->db->table($this->p.'email_test_send_log')->insert(['campaign_id'=>(int)$campaign_id,'contact_id'=>(int)$contact_id,'email'=>strtolower((string)$email),'status'=>$status,'error_details'=>$error,'created_at'=>date('Y-m-d H:i:s')]);}
}
