<?php $filters = $filters ?? []; ?>
<div class="page-title clearfix"><h1><?php echo $campaign ? 'Edit' : 'Create'; ?> Campaign</h1><a class="btn btn-default float-end" href="<?php echo site_url('email_marketing/templates'); ?>">Manage templates</a></div>
<div class="alert alert-warning"><strong>Test mode is enabled.</strong> No campaign email will be sent to normal subscribers. Select one approved CRM contact for testing.</div><div class="card"><div class="card-body"><form method="post" action="<?php echo site_url('email_marketing/save'); ?>">
<input type="hidden" name="<?php echo csrf_token(); ?>" value="<?php echo csrf_hash(); ?>">
<div class="form-group"><label>Campaign name</label><input required class="form-control" name="name" value="<?php echo esc($campaign->name ?? ''); ?>"></div>
<div class="form-group"><label>Subject line</label><input required class="form-control" name="subject" value="<?php echo esc($campaign->subject ?? ''); ?>"></div>
<div class="form-group"><label>Preview text</label><input class="form-control" name="preview_text" value="<?php echo esc($campaign->preview_text ?? ''); ?>"></div>
<div class="form-group"><label>HTML email content</label><textarea required class="form-control" name="html_content" rows="12"><?php echo esc($campaign->html_content ?? ''); ?></textarea><small>Variables: {FIRST_NAME} {LAST_NAME} {FULL_NAME} {EMAIL} {PHONE} {STATE} {POSTCODE} {LEAD_OWNER} {UNSUBSCRIBE_URL} {COMPANY_NAME}</small></div>
<div class="row"><div class="col-md-6"><label>Sender name</label><input class="form-control" name="sender_name" value="<?php echo esc($campaign->sender_name ?? ($settings['default_sender_name'] ?? 'Esteem Energy')); ?>"></div><div class="col-md-6"><label>Reply-to email</label><input type="email" class="form-control" name="reply_to" value="<?php echo esc($campaign->reply_to ?? ($settings['default_reply_to'] ?? '')); ?>"></div></div>
<div class="row mt15"><div class="col-md-6"><label>Send/schedule time</label><input type="datetime-local" class="form-control" name="send_at" value="<?php echo !empty($campaign->send_at) ? date('Y-m-d\\TH:i', strtotime($campaign->send_at)) : ''; ?>"></div><div class="col-md-6"><label>Approved CRM test contact</label><select required class="form-control" name="test_contact_id"><option value="">Select one eligible contact</option><?php foreach(($test_contacts??[]) as $tc): ?><option value="<?php echo (int)$tc->id; ?>" <?php echo ((int)($campaign->test_contact_id??0)===(int)$tc->id)?'selected':''; ?>><?php echo esc(trim($tc->first_name.' '.$tc->last_name).' — '.$tc->email); ?></option><?php endforeach; ?></select><small>Only Opted In, active, non-suppressed, non-Do Not Contact contacts appear.</small></div></div>
<hr><h4>Saved recipient filters</h4><div class="row">
<div class="col-md-3"><label>Type</label><select class="form-control segment" name="type"><option value="">Leads and clients</option><option value="lead" <?php echo (($filters['type'] ?? '') === 'lead') ? 'selected' : ''; ?>>Leads</option><option value="client" <?php echo (($filters['type'] ?? '') === 'client') ? 'selected' : ''; ?>>Clients</option></select></div>
<div class="col-md-3"><label>Owner ID</label><input class="form-control segment" name="owner_id" type="number" value="<?php echo esc($filters['owner_id'] ?? ''); ?>"></div><div class="col-md-3"><label>Lead status ID</label><input class="form-control segment" name="status_id" type="number" value="<?php echo esc($filters['status_id'] ?? ''); ?>"></div><div class="col-md-3"><label>Source ID</label><input class="form-control segment" name="source_id" type="number" value="<?php echo esc($filters['source_id'] ?? ''); ?>"></div>
<div class="col-md-3 mt10"><label>State</label><input class="form-control segment" name="state" value="<?php echo esc($filters['state'] ?? ''); ?>"></div><div class="col-md-3 mt10"><label>Suburb</label><input class="form-control segment" name="suburb" value="<?php echo esc($filters['suburb'] ?? ''); ?>"></div><div class="col-md-3 mt10"><label>Postcode</label><input class="form-control segment" name="postcode" value="<?php echo esc($filters['postcode'] ?? ''); ?>"></div><div class="col-md-3 mt10"><label>Labels</label><input class="form-control segment" name="labels" value="<?php echo esc($filters['labels'] ?? ''); ?>"></div>
<div class="col-md-3 mt10"><label>Created from</label><input class="form-control segment" name="created_from" type="date" value="<?php echo esc($filters['created_from'] ?? ''); ?>"></div><div class="col-md-3 mt10"><label>Created to</label><input class="form-control segment" name="created_to" type="date" value="<?php echo esc($filters['created_to'] ?? ''); ?>"></div></div>
<button type="button" id="preview-recipients" class="btn btn-default mt15">Preview recipients</button><span id="recipient-count" class="ml15"></span><div id="recipient-preview" class="mt15"></div><button class="btn btn-primary mt20">Save Draft (filters saved)</button>
</form></div></div>
<?php if ($campaign): ?><div class="card mt15"><div class="card-body"><h4>Import opted-in contacts from CSV</h4><p>Required columns: <code>email,consent</code>. Optional: <code>first_name,last_name,do_not_contact</code>. Only <strong>Opted In</strong> rows are accepted.</p><form method="post" enctype="multipart/form-data" action="<?php echo site_url('email_marketing/import/'.$campaign->id); ?>"><input type="hidden" name="<?php echo csrf_token(); ?>" value="<?php echo csrf_hash(); ?>"><input required type="file" name="csv_file" accept=".csv,text/csv"><button class="btn btn-default mt10">Import CSV</button></form></div></div><?php endif; ?>
<script>$(function(){var token='<?php echo csrf_hash(); ?>';$('#preview-recipients').on('click',function(){var data={};$('.segment').each(function(){data[this.name]=this.value});data['<?php echo csrf_token(); ?>']=token;$.post('<?php echo site_url('email_marketing/recipients/preview'); ?>',data,function(r){$('#recipient-count').text('Eligible recipients: '+r.count);var h='<table class="table"><tr><th>Name</th><th>Email</th><th>Type</th><th>Location</th></tr>';$.each(r.recipients,function(_,x){h+='<tr><td>'+ $('<div>').text((x.first_name||'')+' '+(x.last_name||'')).html()+'</td><td>'+ $('<div>').text(x.email).html()+'</td><td>'+ $('<div>').text(x.user_type).html()+'</td><td>'+ $('<div>').text((x.state||'')+' '+(x.city||'')+' '+(x.zip||'')).html()+'</td></tr>'});$('#recipient-preview').html(h+'</table>')},'json').fail(function(x){$('#recipient-preview').text('Preview failed: '+x.statusText)})})})</script>
