<?php
namespace Config;
$routes = Services::routes();
$ns = ['namespace' => 'Esteem_Email_Marketing\\Controllers'];
$routes->get('email_marketing', 'Email_Marketing::index', $ns);
$routes->get('email_marketing/dashboard', 'Dashboard::index', $ns);
$routes->get('email_marketing/contacts', 'Contacts::index', $ns);
$routes->get('email_marketing/contacts/export', 'Contacts::export', $ns);
$routes->get('email_marketing/reports', 'Stats::index', $ns);
$routes->get('email_marketing/reports/export', 'Stats::export', $ns);
$routes->get('email_marketing/create', 'Email_Marketing::create', $ns);
$routes->get('email_marketing/edit/(:num)', 'Email_Marketing::edit/$1', $ns);
$routes->get('email_marketing/settings', 'Email_Marketing::settings', $ns);
$routes->get('email_marketing/stats', 'Stats::index', $ns);
$routes->get('email_marketing/automation', 'Email_Marketing::automation', $ns);
$routes->post('email_marketing/recipients/preview', 'Recipients::preview', $ns);
$routes->post('email_marketing/queue/(:num)', 'Campaign_Actions::queue_campaign/$1', $ns);
$routes->post('email_marketing/delete/(:num)', 'Campaign_Actions::delete_campaign/$1', $ns);
$routes->post('email_marketing/import/(:num)', 'Campaign_Actions::import_csv/$1', $ns);
$routes->get('email_marketing/logs/(:num)', 'Campaign_Actions::logs/$1', $ns);
$routes->get('email_marketing/templates', 'Templates::index', $ns);
$routes->get('email_marketing/templates/create', 'Templates::create', $ns);
$routes->get('email_marketing/templates/edit/(:num)', 'Templates::edit/$1', $ns);
$routes->get('email_marketing/templates/preview/(:num)', 'Templates::preview/$1', $ns);
$routes->get('email_marketing/templates/duplicate/(:num)', 'Templates::duplicate/$1', $ns);
$routes->post('email_marketing/templates/save', 'Templates::save', $ns);
$routes->post('email_marketing/templates/delete/(:num)', 'Templates::delete/$1', $ns);
$routes->post('email_marketing/automation/save', 'Automation_Rules::save', $ns);
$routes->get('email_marketing/consent/(:segment)/(:num)', 'Consent::edit/$1/$2', $ns);
$routes->post('email_marketing/consent/save', 'Consent::save', $ns);
$routes->post('email_marketing/(:any)', 'Email_Marketing::$1', $ns);
$routes->post('email_marketing/(:any)/(:num)', 'Email_Marketing::$1/$2', $ns);
$routes->get('email_unsubscribe/(:any)', 'Email_Marketing::unsubscribe/$1', $ns);
